### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by adrianodennanni** [kwerle/ide-ruby#8] opened 2017-12-08 17:47 UTC
Trying to open any file gives me this, after restarting Docker:

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [ide-ruby](https://github.com/kwerle/ide-ruby) package 0.1.6

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /Users/adriano.dennanni/.atom/packages/ide-ruby/node_modules/vscode-jsonrpc/lib/messageReader.js:200

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-ruby/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
    at /packages/ide-ruby/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -4:00.4.0 core:cancel (input.hidden-input)
     -3:58.8.0 tree-view:unfocus (div.tool-panel.tree-view)
     -3:58.6.0 editor:consolidate-selections (input.hidden-input)
     -3:58.6.0 core:cancel (input.hidden-input)
     -2:51.6.0 editor:consolidate-selections (input.hidden-input)
     -2:51.6.0 core:cancel (input.hidden-input)
     -2:48.6.0 core:backspace (input.hidden-input)
     -2:48 core:move-right (input.hidden-input)
  3x -2:47.3.0 core:backspace (input.hidden-input)
     -2:40.5.0 core:save (input.hidden-input)
     -2:33.9.0 tree-view:move (span.name.icon.icon-file-text)
     -2:31.7.0 core:backspace (input.hidden-input)
     -2:31.3.0 core:move-right (input.hidden-input)
     -2:30.7.0 core:backspace (input.hidden-input)
     -2:29.9.0 core:confirm (input.hidden-input)
     -0:05.3.0 tree-view:remove (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-byebug 0.1.4 
atom-ide-ui 0.6.0 
busy-signal 1.4.3 
file-type-icons 1.3.4 
goto-definition 1.3.4 
hashrocket 0.4.10 
ide-ruby 0.1.6 
intentions 1.1.5 
language-csv 1.1.2 
language-docker 1.1.8 
language-dotenv 1.1.1 
language-gitignore 0.3.0 
language-log 1.9.0 
linter 2.2.0 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
monokai 0.24.0 
multi-wrap-guide 1.0.0 
multifile-rename 0.1.6 
pigments 0.40.2 
prompt-big-file 0.4.0 
remote-atom 1.3.11 
tablr 1.8.3 
trailing-spaces 0.4.0 
```

**Comment by kwerle** [comment] 2017-12-08 20:01
Huh.  That's a new one on me.  Has it worked for you for any file?  For any project?

Can you open a folder with just one ruby file in it, and does that work?

I really don't know what's going on with this one.

**Comment by adrianodennanni** [comment] 2017-12-08 20:34
I'm afraid I can't reproduce that anymore. In the present time, it is
working fine.

2017-12-08 18:01 GMT-02:00 Kurt Werle <notifications@github.com>:

**Comment by kwerle** [comment] 2017-12-08 21:06
OK - I'm going to close this - but if you can reproduce it, I'd sure like to hear about it.

**Comment by kwerle** [comment] 2018-11-13 01:28
Hmm.  Now I'm seeing it for everything.  Looks like it might have to do with using stdio and possibble noise instead of IPC.  I'd much prefer IPC - I'll take another stab at it.

**Closed** 2021-05-21 05:37 UTC
